apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: true
  - name: yesoreyeram-infinity-datasource
    type: yesoreyeram-infinity-datasource
    jsonData:
      allowedHosts:
        - "docs.google.com"
